---
title: "QCA Assignment 3"
author: "Akira Sasaki"
date: "29/04/2017"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(knitr)
opts_chunk$set(message = FALSE, error = TRUE, fig.pos = 'H', tidy.opts=list(width.cutoff=65), tidy=TRUE, fig.path='figs/', cache.path='cache/graphics-', 
           fig.align='center', fig.width = 5, fig.height = 4, fig.show = 'hold',
           cache = TRUE, par = TRUE)
```

```{r setting, include=FALSE, echo=FALSE}

install.packages("quanteda")
library(quanteda)
library(readxl)
library(tm)
MACRONLEPEN <- read_excel("~/Dropbox/Quantitative Content Analysis/Dataset-MACRONLEPEN.xlsx")
Corpus <- Corpus(VectorSource(MACRONLEPEN$text))
Dfm <- dfm(Corpus, tolower = T, stem = T, removePunct = T,
           removeNumbers = T, removeSymbols = T, 
           remove = stopwords("french"))


```

```{r}
rm(list = ls())

Corpus2 <-  tm_map(Corpus, tolower)
Corpus3 <-  tm_map(Corpus2, removeWords, stopwords("french"))
Corpus4 <-  tm_map(Corpus3, removePunctuation)
```

